MVCApiSeriesPersonajes2023/Models/ErrorViewModel.cs
namespace MVCApiSeriesPersonajes2023.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCApiSeriesPersonajes2023/Models/Personaje.cs
namespace MVCApiSeriesPersonajes2023.Models
{
    public class Personaje
    {
        public int IdPersonaje { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public int IdSerie { get; set; }

    }
}

MVCApiSeriesPersonajes2023/Models/Serie.cs
namespace MVCApiSeriesPersonajes2023.Models
{
    public class Serie
    {
        public int IdSerie { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public int Anyo { get; set; }

    }
}

MVCApiSeriesPersonajes2023/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApiSeriesPersonajes2023.Models;
using System.Diagnostics;

namespace MVCApiSeriesPersonajes2023.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCApiSeriesPersonajes2023/Controllers/PersonajesController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApiSeriesPersonajes2023.Helpers;
using MVCApiSeriesPersonajes2023.Models;
using MVCApiSeriesPersonajes2023.Services;

namespace MVCApiSeriesPersonajes2023.Controllers
{
    public class PersonajesController : Controller
    {
        private ServiceSeries service;
        private HelperPathProvider helperPath;
        public PersonajesController(ServiceSeries series, HelperPathProvider helperPath)
        {
            this.service = series;
            this.helperPath = helperPath;
        }


        public async Task<IActionResult> PersonajesSerie(int idserie)
        {
            List<Personaje> personajes = await this.service.FindPersonajesSerieAsync(idserie);
            return View(personajes);

        }

        public async Task<IActionResult> CreatePersonaje()
        {
            List<Serie> series = await this.service.GetSeriesAsync();
            ViewData["SERIES"] = series;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePersonaje(Personaje personaje, IFormFile fichero)
        {
            //subir el fichero al servidor
            string fileName = fichero.FileName;
            string path = this.helperPath.GetMapPath(Folders.Imagenes, fileName);
            using (Stream stream = new FileStream(path, FileMode.Create))
            {
                await fichero.CopyToAsync(stream);
            }
            //Guardamos en el api la url del servidor con la imagen
            string folder = this.helperPath.GetNameFolder(Folders.Imagenes);
            personaje.Imagen = this.helperPath.GetWebHostUrl() + folder + "/" + fileName;
            await this.service.CreatePersonajeAsync(personaje.IdPersonaje, personaje.Nombre, personaje.IdSerie, personaje.Imagen);
            return RedirectToAction("PersonajesSerie", new { idserie = personaje.IdSerie });
        }

        
        public async Task<IActionResult> UpdatePersonajeSerie()
        {
            List<Personaje> personajes = await this.service.GetPersonajesAsync();
            List<Serie> series = await this.service.GetSeriesAsync();
            ViewData["PERSONAJES"] = personajes;
            ViewData["SERIES"] = series;
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> UpdatePersonajeSerie(int idpersonaje, int idserie)
        {
            await this.service.UpdateSeriePersonajeAsync(idpersonaje, idserie);
            return RedirectToAction("PersonajeSerie", new {idserie = idserie});
        }
    }
}

MVCApiSeriesPersonajes2023/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApiSeriesPersonajes2023.Services;
using MVCApiSeriesPersonajes2023.Models;

namespace MVCApiSeriesPersonajes2023.Controllers
{
    public class SeriesController : Controller
    {
        private ServiceSeries service;

        public SeriesController(ServiceSeries service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Serie> series = await this.service.GetSeriesAsync();
            return View(series);
        }

        
        public async Task<IActionResult> Detalles(int idserie)
        {
            Serie serie = await this.service.FindSeriesAsync(idserie);
            return View(serie);
        } 
        
    }
}

MVCApiSeriesPersonajes2023/ViewComponents/MenuSeriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCApiSeriesPersonajes2023.Models;
using MVCApiSeriesPersonajes2023.Services;

namespace MVCApiSeriesPersonajes2023.ViewComponents
{
    public class MenuSeriesViewComponent: ViewComponent
    {
        private ServiceSeries service;

        public MenuSeriesViewComponent(ServiceSeries service)
        {
            this.service = service;
        }

        //EL METODO InvokeAsync() ES EL ENCARGAO DE ENVIAR UN MODEL AL LAYOUT
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Serie> series = await this.service.GetSeriesAsync();
            return View(series);
        }


    }
}

MVCApiSeriesPersonajes2023/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCApiSeriesPersonajes2023/Views/Personajes/CreatePersonaje.cshtml
@model MVCApiSeriesPersonajes2023.Models.Personaje
@{
    List<Serie> series = ViewData["SERIES"] as List<Serie>;
}
@{
    ViewData["Title"] = "CreatePersonaje";
}

<h1>Crear un personaje</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersonaje" class="control-label"></label>
                <input asp-for="IdPersonaje" class="form-control" />
                <span asp-validation-for="IdPersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Imagen del personaje: </label>
                <input type="file" name="fichero" class="form-control"/>
            </div>
            <div class="form-group">
                <label class="control-label">Seleccione Serie</label>
                <select class="form-control" name="idserie">
                    @foreach (Serie serie in series)
                    {
                        <option value="@serie.IdSerie">@serie.Nombre</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCApiSeriesPersonajes2023/Views/Personajes/PersonajesSerie.cshtml
@model List<Personaje>

<h1>Personajes Serie</h1>

<table class="table table-dark">
    <thead>
        <tr>
            <th>Personaje</th>
            <th>Imagen</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Personaje person in Model)
        {
            <tr>
                <td>
                    <img src="@person.Imagen"
                         style="width: 100px; height: 100px;"/>
                </td>
                <td class="card-body">
                     <h5 class="card-title">@person.Nombre</h5>                   
                </td>
            </tr>

        }
    </tbody>
</table>

MVCApiSeriesPersonajes2023/Views/Personajes/UpdatePersonajeSerie.cshtml
@{
    List<Personaje> personajes = ViewData["PERSONAJES"] as List<Personaje>;
    List<Serie> series = ViewData["SERIES"] as List<Serie>;
}

<h1>Cambiar personaje de serie</h1>

<form method="post">
    <label>Seleccione un personaje</label>
    <select class="form-control" name="idpersonaje">
        @foreach (Personaje person in personajes)
        {
                <option value="@person.IdPersonaje">@person.Nombre</option>
        }
    </select>
    <label>Seleccione una serie</label>
    <select class="form-control" name="idserie">
        @foreach (Serie serie in series)
        {
                <option value="@serie.IdSerie">@serie.Nombre</option>
        }
    </select>
    <button class="btn btn-warning">
        Cambiar personaje de serie
    </button>
</form>

MVCApiSeriesPersonajes2023/Views/Series/Detalles.cshtml
@model Serie

<h1>Detalles Serie</h1>

<a class="btn btn-dark" asp-controller="Series"
    asp-action="Index">
    Volver a Series
</a>

<div class="card" style="width: 18rem;">
    <img src="@Model.Imagen" class="card-img-top" alt="..." />
    <div class="card-body">
        <h5 class="card-title">@Model.Nombre</h5>
        <p class="card-text">Año: @Model.Anyo</p>
        <a asp-controller="Personajes"
            asp-action="PersonajesSerie"
            asp-route-idserie="@Model.IdSerie"
            class="btn btn-primary">Personajes</a>
    </div>
</div>

MVCApiSeriesPersonajes2023/Views/Series/Index.cshtml
@model List<Serie>

<h1>Series</h1>

<ul class="list-group">
    @foreach (Serie serie in Model)
    {
        <li class="list-group-group-item">
            <a asp-controller="Series"
            asp-action="Detalles"
            asp-route-idserie="@serie.IdSerie">
                @serie.Nombre
            </a>
        </li>
    }
</ul>

MVCApiSeriesPersonajes2023/Views/Shared/Components/MenuSeries/Default.cshtml
@model List<Serie>

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Series
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        @foreach (Serie serie in Model)
        {
            <li><a class="dropdown-item" asp-controller="Series" asp-action="Detalles" asp-route-idserie="@serie.IdSerie">@serie.Nombre</a></li>
        }       
    </ul>
</div>

MVCApiSeriesPersonajes2023/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApiSeriesPersonajes2023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCApiSeriesPersonajes2023.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCApiSeriesPersonajes2023</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Personajes" asp-action="CreatePersonaje">Nuevo Personaje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Personajes" asp-action="UpdatePersonajeSerie">Cambiar personaje de serie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Series" asp-action="Index">Series</a>
                        </li>
                        <li>
                           @await Component.InvokeAsync("MenuSeries")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>2
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCApiSeriesPersonajes2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>